#!/usr/bin/env bash

HADOOP_HOME="${HADOOP_HOME:?You should set HADOOP_HOME}"
EXPAT_HADOOP_SHARE=${HADOOP_HOME}/share/hadoop

HADOOP_USER_NAME="${HADOOP_USER_NAME:?You should set HADOOP_USER_NAME}"
HOPSWORKS_EAR_HOME="${HOPSWORKS_EAR_HOME:?You should set HOPSWORKS_EAR_HOME}"

dirname=$(dirname "$0")
export CLASSPATH=$dirname/../etc/:$dirname/../lib/*:$EXPAT_HADOOP_SHARE/hdfs/*:$EXPAT_HADOOP_SHARE/common/*:$HOPSWORKS_EAR_HOME/lib/*:$HADOOP_HOME/etc/hadoop

java -cp $CLASSPATH io.hops.hopsworks.expat.Expat $@
